# Generated by Django 3.1.3 on 2020-11-14 03:05

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cartegory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('Polictics', 'Polictics'), ('World', 'World'), ('Religion', 'Religion'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Medical', 'Medical'), ('Sport', 'Sport')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Newsmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_url', models.CharField(blank=True, max_length=1000, null=True)),
                ('heading', models.CharField(max_length=300)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('article_img', models.CharField(blank=True, max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('view', models.IntegerField(default=0)),
                ('post', models.BooleanField(default=False)),
                ('newscat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='news.cartegory')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site', models.TextField(null=True)),
                ('icon', models.ImageField(upload_to='article_image')),
            ],
        ),
        migrations.DeleteModel(
            name='News',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='news.source'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.newsmodel'),
        ),
        migrations.AddField(
            model_name='comment',
            name='us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
