# Generated by Django 3.1.3 on 2020-11-27 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20201122_0423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='source',
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
