# Generated by Django 3.1.3 on 2020-11-27 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201127_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmodel',
            name='source',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
