# Generated by Django 3.1.3 on 2020-11-28 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsmodel_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsmodel',
            name='newscat',
        ),
        migrations.AddField(
            model_name='newsmodel',
            name='newscat',
            field=models.ManyToManyField(null=True, to='news.cartegory'),
        ),
    ]
