# Generated by Django 3.1.3 on 2020-12-05 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20201128_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartegory',
            name='cat',
            field=models.CharField(choices=[('News', 'News'), ('Polictics', 'Polictics'), ('World', 'World'), ('Religion', 'Religion'), ('Education', 'Education'), ('Fashion', 'Fashion'), ('Technology', 'Technology'), ('Entertainment', 'Entertainment'), ('Medical', 'Medical'), ('Sport', 'Sport')], max_length=15),
        ),
        migrations.AlterField(
            model_name='newsmodel',
            name='newscat',
            field=models.ManyToManyField(to='news.cartegory'),
        ),
    ]
